import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import AuthProvider from "../context/AuthProvider";
import StoreProvider from "@/context/StoreProvider";

const poppins = Poppins({
	subsets: ["latin"],
	weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<AuthProvider>
			<StoreProvider>
				<html lang="en">
					<body
						className={`min-h-screen w-screen bg-background text-foreground dark ${poppins.className} antialiased`}
					>
						{children}
					</body>
				</html>
			</StoreProvider>
		</AuthProvider>
	);
}
